name: Test Microk8s
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to install MicroK8s
    steps:
    - uses: balchua/microk8s-actions@v0.1.2
      with:
        channel: 'latest/stable'
    - name: Test MicroK8s
      id: myactions
      run: |
        kubectl get no
        kubectl get pods -A -o wide
        kubectl apply -f deploy/nginx.yaml
