name: Test Microk8s
on:
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Install MicroK8s
    steps:
    - uses: balchua/microk8s-actions@v0.1.2
      with:
        channel: 'latest/stable'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test nginx
      id: microk8snginx
      run: |
        set -x
        ls
        pwd
        kubectl get no
        kubectl get pods -A -o wide
        kubectl apply -f ${{ github.workspace }}/deploy/nginx.yaml
